# Generated by Django 3.2.11 on 2023-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('detail', models.CharField(blank=True, max_length=50)),
                ('detail_name', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('show_qrcode', models.BooleanField(default=False)),
            ],
        ),
    ]
