# Generated by Django 4.0.3 on 2023-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='logo',
            field=models.ImageField(upload_to='payment_method_logo'),
        ),
    ]
