# Generated by Django 3.2.11 on 2023-03-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportedcurrency',
            old_name='currency',
            new_name='symbol',
        ),
    ]
