# Generated by Django 3.2.11 on 2023-03-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_supportedcurrency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.measurementunit'),
        ),
    ]
