# Generated by Django 4.0.3 on 2023-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_product_thumbnail_product_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.TextField(help_text='Keywords separated by comma', null=True),
        ),
    ]
