# Generated by Django 4.0.3 on 2023-03-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productimages_color_productimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='color',
        ),
    ]
