# Generated by Django 4.0.3 on 2023-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_productimages_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='color',
            field=models.CharField(default='', help_text='Color code for e.g #000000 is black', max_length=9),
            preserve_default=False,
        ),
    ]
