# Generated by Django 4.0.3 on 2023-03-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productimages_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Color', 'color'), ('Size', 'size')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('parent_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productfeature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='inventory.product')),
            ],
            options={
                'unique_together': {('type', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='inventory.productfeature')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Mobile', 'mobile'), ('Tablet', 'tablet'), ('Desktop', 'desktop')], max_length=20)),
                ('image', models.ImageField(upload_to='product_variation_images')),
                ('thumbnail', models.ImageField(upload_to='production_variation_thumbnails')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_variation_image', to='inventory.productvariation')),
            ],
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product_image',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='inventory.productprice'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='inventory.product'),
        ),
    ]
