# Generated by Django 4.0.3 on 2023-03-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_productvariationimage_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.supportedcurrency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.measurementunit'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productvariationimage',
            name='product_variation_device_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariationdeviceimage'),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
