# Generated by Django 4.0.3 on 2023-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_tag_category_keywords_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='product', to='inventory.tag'),
        ),
    ]
