# Generated by Django 4.0.3 on 2023-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_productfeature_name_alter_productfeature_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
    ]
