# Generated by Django 4.0.3 on 2023-03-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_productvariation_discount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together={('type', 'value', 'product')},
        ),
    ]
