# Generated by Django 4.0.3 on 2023-03-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_productfeature_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariationimage',
            name='product_variation_device_image',
        ),
        migrations.AddField(
            model_name='productvariationimage',
            name='product_variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='production_variation_image', to='inventory.productvariation'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductVariationDeviceImage',
        ),
    ]
