# Generated by Django 3.2.11 on 2023-03-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='anonymous_customer',
        ),
    ]
