# Generated by Django 3.2.11 on 2023-03-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamesales', '0001_initial'),
        ('sales', '0003_remove_cart_anonymous_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='gamesales.anonymouscustomer'),
        ),
    ]
