# Generated by Django 4.0.3 on 2023-03-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sales', '0004_cart_anonymous_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='anonymous_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customer.anonymouscustomer'),
        ),
    ]
